import { type ICommand } from '.';
import { divider } from './divider';
import { group } from './group';
declare let bold: ICommand;
declare let code: ICommand;
declare let codeBlock: ICommand;
declare let comment: ICommand;
declare let fullscreen: ICommand;
declare let hr: ICommand;
declare let image: ICommand;
declare let italic: ICommand;
declare let link: ICommand;
declare let checkedListCommand: ICommand;
declare let orderedListCommand: ICommand;
declare let unorderedListCommand: ICommand;
declare let codeEdit: ICommand;
declare let codeLive: ICommand;
declare let codePreview: ICommand;
declare let quote: ICommand;
declare let strikethrough: ICommand;
declare let issue: ICommand;
declare let title: ICommand;
declare let title1: ICommand;
declare let title2: ICommand;
declare let title3: ICommand;
declare let title4: ICommand;
declare let title5: ICommand;
declare let title6: ICommand;
declare let table: ICommand;
declare let help: ICommand;
export declare const getCommands: () => ICommand[];
export declare const getExtraCommands: () => ICommand[];
export { title, title1, title2, title3, title4, title5, title6, bold, codeBlock, comment, italic, strikethrough, hr, group, divider, link, quote, code, image, unorderedListCommand, orderedListCommand, checkedListCommand, table, issue, help, codeEdit, codeLive, codePreview, fullscreen, };
